/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.UI;

import com.graphing.GraphTools;
import com.graphing.GraphWrapper;
import com.graphing.Node;
import com.mxgraph.util.mxConstants;
import com.mxgraph.view.mxGraph;
import com.mxgraph.view.mxStylesheet;
import java.awt.Frame;
import java.awt.Toolkit;
import java.util.HashMap;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author ericcastro
 */
public class MainView extends javax.swing.JFrame 
{

    /**
     * Creates new form GraphView
     */
    public MainView() 
    {
        initComponents();
        
        nodeSlider.setMinimum(1);
        nodeSlider.setMaximum(20);
        nodeSlider.setMajorTickSpacing(1);
        nodeSlider.setSnapToTicks(true);
        nodeSlider.setValue(10);
        nodeSlider.addChangeListener((ChangeEvent e) -> {
            int value = nodeSlider.getValue();
            nodeSizeLabel.setText(value+"");
            
            edgeSlider.setMinimum(value-1);
            edgeSlider.setMaximum(value * (value - 1));
            edgeSlider.setValue(value - 1);
        });
        
        
        edgeSlider.setSnapToTicks(true);
        edgeSlider.addChangeListener((ChangeEvent e) -> {
            int value = edgeSlider.getValue();
            edgeSizeLabel.setText(value+"");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nodeSlider = new javax.swing.JSlider();
        nodesLabel = new javax.swing.JLabel();
        algorithmsLabel = new javax.swing.JLabel();
        dfsButton = new javax.swing.JButton();
        bfsButton = new javax.swing.JButton();
        nodeSizeLabel = new javax.swing.JLabel();
        edgeSlider = new javax.swing.JSlider();
        edgeSizeLabel = new javax.swing.JLabel();
        edgesLabel = new javax.swing.JLabel();
        creditLabel = new javax.swing.JLabel();
        mainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        quiteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graph Visualizer");

        nodeSlider.setMajorTickSpacing(5);
        nodeSlider.setMaximum(20);
        nodeSlider.setMinimum(1);
        nodeSlider.setMinorTickSpacing(1);
        nodeSlider.setSnapToTicks(true);

        nodesLabel.setText("Nodes:");

        algorithmsLabel.setText("Algorithms");

        dfsButton.setText("Depth First Search");
        dfsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dfsButtonActionPerformed(evt);
            }
        });

        bfsButton.setText("Breadth First Search");
        bfsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfsButtonActionPerformed(evt);
            }
        });

        nodeSizeLabel.setText("10");

        edgeSlider.setMajorTickSpacing(5);
        edgeSlider.setMaximum(90);
        edgeSlider.setMinimum(9);
        edgeSlider.setMinorTickSpacing(1);
        edgeSlider.setSnapToTicks(true);
        edgeSlider.setToolTipText("");
        edgeSlider.setValue(9);

        edgeSizeLabel.setText("9");

        edgesLabel.setText("Edges:");

        creditLabel.setText("Castro, Yee 2014");

        fileMenu.setText("File");

        quiteMenuItem.setText("Quit");
        quiteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiteMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(quiteMenuItem);

        mainMenu.add(fileMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        mainMenu.add(helpMenu);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nodesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nodeSizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edgesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edgeSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edgeSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nodeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(algorithmsLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bfsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dfsButton)))
                            .addComponent(creditLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nodesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nodeSizeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nodeSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edgesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(edgeSizeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edgeSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(algorithmsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dfsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bfsButton)
                .addGap(175, 175, 175)
                .addComponent(creditLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dfsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dfsButtonActionPerformed
        GraphWrapper wrapper = GraphTools.generateGraph(nodeSlider.getValue(), 
                                                        edgeSlider.getValue());
        
        GraphView frame = new GraphView(wrapper, GraphView.DFS);
        displayFrame(frame);
    }//GEN-LAST:event_dfsButtonActionPerformed

    private void bfsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfsButtonActionPerformed
        GraphWrapper wrapper = GraphTools.generateGraph(nodeSlider.getValue(), 
                                                        edgeSlider.getValue());
        
        GraphView frame = new GraphView(wrapper, GraphView.BFS);
        displayFrame(frame);
    }//GEN-LAST:event_bfsButtonActionPerformed

    private void quiteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiteMenuItemActionPerformed
        
    }//GEN-LAST:event_quiteMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        AboutFrame frame = new AboutFrame();
        displayFrame(frame);
    }//GEN-LAST:event_aboutMenuItemActionPerformed
    
    private void displayFrame(Frame frame)
    {
        int screenWidth = Toolkit.getDefaultToolkit().getScreenSize().width - frame.getWidth();
        int screenHeight = Toolkit.getDefaultToolkit().getScreenSize().height - frame.getHeight();
        
        int x = (screenWidth)/2;
        int y = (screenHeight)/2;
       
        frame.setLocation(x, y);      
        frame.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macintosh".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                MainView view = new MainView();
                int x = (Toolkit.getDefaultToolkit().getScreenSize().width - view.getWidth())/2;
                int y = (Toolkit.getDefaultToolkit().getScreenSize().height - view.getHeight())/2;
        
                view.setLocation(x, y);     
                view.setVisible(true);
                view.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JLabel algorithmsLabel;
    private javax.swing.JButton bfsButton;
    private javax.swing.JLabel creditLabel;
    private javax.swing.JButton dfsButton;
    private javax.swing.JLabel edgeSizeLabel;
    private javax.swing.JSlider edgeSlider;
    private javax.swing.JLabel edgesLabel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JLabel nodeSizeLabel;
    private javax.swing.JSlider nodeSlider;
    private javax.swing.JLabel nodesLabel;
    private javax.swing.JMenuItem quiteMenuItem;
    // End of variables declaration//GEN-END:variables
}
